namespace ber {
	enum Tag {
		EOC, BOOLEAN, INTEGER, BIT_STRING, OCTET_STRING, NULL_TYPE,
		OBJECT_IDENTIFIER, OBJECT_DESCRIPTOR, EXTERNAL, REAL, ENUMERATED,
		EMBEDDED_PDV, UTF8STRING, RELATIVE_OID, RESERVED1, RESERVED2, SEQUENCE,
		SET, NUMERIC_STRING, PRINTABLE_STRING, T61_STRING, VIDEOTEX_STRING, 
		IA5_STRING, UTCTIME, GENERALIZED_TIME, GRAPHIC_STRING, VISIBLE_STRING, 
		GENERAL_STRING, UNIVERSAL_STRING, CHARACTER_STRING, BMP_STRING
	};

	enum Class {
		UNIVERSAL, APPLICATION, CONTEXT_SPECIFIC, PRIVATE
	};

	enum PC {
		PRIMITIVE, CONSTRUCTED
	};

	struct Type {
		Tag tag;
		Class cls;
		PC pc;
	};
}




